### ISSUE TITLE
Formatage

### ISSUE THREAD

**Issue by mathieubellon** [hbyio/draaft#13]
- [x] Les noms de dossiers / fichiers ne doivent pas avoir d'accents
- [ ] Les dates ne doivent pas être des string

**Comment by thomasWajs** [comment]
> Les dates ne doivent pas être des string

@mathieubellon Peux-tu me préciser l'emplacement des dates, et le format attendu stp ?

**Comment by mathieubellon** [comment]
Stand by sur cette histoire de dates, apparemment le bug ne vient pas du frontmatter tel que généré par draaft actuellement

**Comment by thomasWajs** [comment]
Ok, donc je ferme le ticket, on rouvrira si besoin
